name: Building the web app

on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: setup dotnet core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '6.0.x'
          include-prerelease: true    
      - run: |
          dotnet restore
          dotnet build
          dotnet pack -v normal -c Release --include-source -p:PackageVersion=$Version -o nupkg
      - uses: actions/upload-artifact@v2
        with:
          name: my-artifact
          path: nupkg